### ISSUE TITLE
No build with fresh katydid/katydid

### ISSUE THREAD

**Issue by tnako** [katydid/relaxng#3]
With fresh katydid/katydid/relapse/* have next errors:
> go test -v .
> ./funcs.go:35:74: cannot use token literal (type *token) as type *ast.Expr in argument to combinator.Value
> ./funcs.go:135:53: cannot use whitespace literal (type *whitespace) as type *ast.Expr in argument to combinator.Value
> ./funcs.go:139:53: cannot use whitespace literal (type *whitespace) as type *ast.Expr in argument to combinator.Value
> ./funcs.go:143:50: cannot use anytext literal (type *anytext) as type *ast.Expr in argument to combinator.Value
> ./funcs.go:147:77: cannot use text literal (type *text) as type *ast.Expr in argument to combinator.Value
> ./funcs.go:223:73: cannot use list literal (type *list) as type *ast.Expr in argument to combinator.Value`

**Comment by tnako** [comment]
With https://github.com/katydid/katydid/tree/53132d61ec301e6b7fe70ac361f5a81729100574 tests are OK

**Comment by awalterschulze** [comment]
I was unaware I had any users :)
I'll make sure to fix this asap.
This is great news thanks for reporting.

**Comment by awalterschulze** [comment]
Fixed.

Maybe I ask where you using it ?

**Comment by awalterschulze** [comment]
https://github.com/katydid/relaxng/commit/311dfeb8ff0a0691f66d63613a00f0add32ae5a6

**Comment by tnako** [comment]
Thank you!
> Maybe I ask where you using it ?
I have big XMLs and RNG discrube internal structure. And want to to load this XML into Go memory. But need something to sync then RNG<->Go structs for future fast changes

**Comment by awalterschulze** [comment]
Interesting.
Please let me know if this tool helps you and what you think can be added to help you more.

I assume then you are using katydid/relapse as well?
